#!/bin/env python
# Copyright 2024-2025 KillZwitch Team
# https://github.com/kzcz
# Author: kzzc@proton.me
# This file is licensed under the GPL version 3 and later

# Note for bug seekers : files that import other files might not work because the dependencies might not be installed, it
# is recommended you inline the code you import to avoid crashes or bugs.
from random import choice
from base import ask
import gzip, zlib, lzma, sys, ast
from typing import Never
def die(msg: str, err: int = 1) -> Never:
    print(msg)
    sys.exit(err)
def c_gzip(stream: str) -> bytes:
    return gzip.compress(stream.encode("utf-8"),compresslevel=9)
def c_zlib(stream: str) -> bytes:
    cmp = zlib.compressobj(level=9, memLevel=9, method=zlib.DEFLATED, wbits=zlib.MAX_WBITS, strategy=zlib.Z_FILTERED)
    return cmp.compress(stream.encode("utf-8")) + cmp.flush()
def c_lzma(stream: str) -> bytes:
    return lzma.compress(stream.encode("utf-8"),preset=lzma.PRESET_EXTREME)
algs={"gzip": c_gzip, "zlib": c_zlib, "lzma": c_lzma}
files: dict[str,bytes]={}
def check(stream: str) -> Exception | str:
    try: ast.unparse(ast.parse(stream))
    except Exception as e: return e
    return stream
def pull(file: str) -> str:
    with open(file) as f:
        cnt: str = f.read()
        return cnt
def chk_comp(file: str, comp: str) -> bytes:
    if comp not in algs: die("Invalid compressor")
    try:
        n=check(pull(file))
        if type(n)!=str:
            print("That file, ({f}) has invalid python code.")
            return b''
        return algs[comp](n)
    except FileNotFoundError: print("The file doesn't exist.")
    except PermissionError: print("You don't have permission to open that file.")
    except IsADirectoryError: print("That path was a directory.")
    except Exception as e: print(f"Unexpected error: {e!r}")
    return b''

def pack(files: dict[str,bytes], calg: str, reqpkg: list[str], note: str):
    fmt_fcnt=lambda lns: f"""# Warning: this file contains binary data that might get corrupted
# Do not edit this file unless you know what you're doing
W=globals().copy()
import {calg}
W.update({{'__name__':'__main__'}})
{lns}
a={files}
print('files in this archive: {', '.join(files.keys())}')
if (f:=input('enter file to execute: ')) not in a: exit('File not found.')
exec({calg}.decompress(a[f]),W,W)"""
    _lns=''
    if note: _lns+=f"print('note: '{note!r})\n"
    if reqpkg: _lns+=f"from importlib.metadata import distributions as dist\ninst_pkgs = {{pkg.metadata['Name'].lower() for pkg in dist()}}\nmissing_pkgs = [pkg for pkg in {reqpkg} if pkg.lower() not in inst_pkgs]\nif missing_pkgs: exit('Missing packages:'+' '.join(missing_pkgs))\n"
    return fmt_fcnt(_lns)
lsav=len(sys.argv)
if lsav>1:
    if lsav==2 and sys.argv[1] in ['--help','-h','help']:
        print(f"Usage #1: {sys.argv[0]} (Interactive)")
        print(f"Usage #2: {sys.argv[0]} --help (help)")
        print(f"Usage #3: {sys.argv[0]} [gzip|zlib|lzma] <outfile.py> <in_1.py> <in_2.py> [...]")
        sys.exit(0)
    if lsav < 4: die(f"Invalid arguments. Try {sys.argv[0]} --help.")
    comp=sys.argv[1]
    if comp not in algs: die(f"{comp} is not a valid compression algorithm.")
    outf=sys.argv[2]
    if not outf.endswith(".py"): die("Output file should end with '.py'")
    for f in sys.argv[3:]:
        if not f.endswith(".py"): die("Input files should end with '.py'")
        if f in files:
            print(f"File {f} is repeated.")
            continue
        rst=chk_comp(f, comp)
        if rst==b'': continue
        files[f]=rst
    try:
        with open(outf,"w") as of:
            of.write(pack(files,comp,[],''))
            of.close()
    except Exception as e:
        die(f"Got exception {e!r} while writing to {outf}")
    
else:
    print("Copyright 2024 KillZwitch Team")
    print("What compressor do you want to use? [gzip, zlib or lzma, empty selects a random one]")
    if (comp:=input("> ").strip().lower()) not in (*algs, ""): exit("choose a valid algorithm")
    if not comp:
        comp=choice(list(algs.keys()))
        print("Randomly selected: "+comp)
    outf=input("Enter output file > ").strip()
    pkgl=[]
    nt=''
    print("Put every file in a new line, you may use absolute or relative paths")
    while f:=input("Files > ").strip():
        if f in files:
            print(f+" was already selected, try a different file.")
            continue
        rst=chk_comp(f, comp)
        if rst==b'': continue
        files[f]=rst
    if not files: die("Can't create an empty archive.")
    print(f"Files that will be added: {' '.join(files.keys())}")
    if ask("Require packages to be installed",False):
        pkgl=[]
        print("Enter only a single package per line.")
        while pk:=input("Packages > ").strip().lower():
            if pk in pkgl:
                print("That package is already set to be required.")
                continue
            pkgl.append(pk)
        if not pkgl: print("Skipping: Empty require list.")
        else: print(f"packages that will be needed: {' '.join(pkgl)}")    
    if ask("Add a comment",False):
        nt=input('Enter the comment to add to the archive > ').strip()
        if not nt: print("Skipping: Empty note.")
    try:
        with open(outf,"w") as of:
            of.write(pack(files,comp,pkgl,nt))
    except Exception as e:
        die(f"Got exception {e!r} while writing to {outf}")
    
